services:
  ai-translation-worker:
    image: ghcr.io/phanmanhcuongdev/translation-ai-worker:main
    container_name: ai-translation-worker
    env_file:
      - stack.env
    ports:
      - "8000:8000"
    pull_policy: always
    restart: unless-stopped
